name: Build

on:
  push:
    branches: [ workflow ]
  pull_request:
    branches: [ workflow ]

env:
  CARGO_TERM_COLOR: always
  VCPKG_ROOT: 'C:\vcpkg'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore vcpkg Cache
        uses: actions/cache@v3
        with:
          path: C:\vcpkg\installed
          key: vcpkg-libarchive-x64-windows-static-md
      - name: Setup vcpkg
        run: |
          vcpkg integrate install
          vcpkg install libarchive:x64-windows-static-md
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build Release
        run: .\\build-release.bat